# Generated by Django 4.2.30 on 2026-06-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер стола")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=4, verbose_name="Вместимость"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Свободен"),
                            ("occupied", "Занят"),
                            ("reserved", "Забронирован"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurants.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
                "ordering": ["number"],
                "unique_together": {("restaurant", "number")},
            },
        ),
    ]
