# Generated by Django 4.2.30 on 2026-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("logo", models.ImageField(upload_to="restaurants/logos/")),
                ("is_active", models.BooleanField(default=True)),
                ("currency", models.CharField(default="RUB", max_length=3)),
            ],
        ),
    ]
