# Generated by Django 4.2.30 on 2026-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(blank=True, upload_to="restaurants/logos/"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
