# Generated by Django 4.2.30 on 2026-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание оплаты"),
                    ("paid", "Оплачен"),
                    ("failed", "Оплата не удалась"),
                    ("refunded", "Возврат средств"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
